export const sidebarLinks = [
  {
    label: "Dashboard",
    route: "/",
    icon: "/dash.svg",
  },
  {
    label: "My Profile",
    route: "/profile",
    icon: "/profile.svg",
  },
  {
    label: "Favorites",
    route: "/favorites",
    icon: "/fav.svg",
  },
  {
    label: "My Mutuals",
    route: "/mutual",
    icon: "/agree.svg",
  },
  {
    label: "My Subscribed",
    route: "/subscribe",
    icon: "/bill.svg",
  },
  {
    label: "Interested in me",
    route: "/interest",
    icon: "/romance.svg",
  },
  {
    label: "Settings",
    route: "/settings",
    icon: "/settings.svg",
  },
  {
    label: "Logout",
    route: "/logout",
    icon: "/Shutdown.svg",
  },
];

export const users = [
  {
    name: "Davina",
    age: 23,
    location: "Abuja",
    match: "85%",
    verified: true,
    read: true,
    red: true,
    bg: "/profile_one_bg.svg",
    icon: "/profile_round_one.svg",
  },
  {
    name: "Emeka",
    age: 28,
    location: "Lagos",
    match: "92%",
    verified: true,
    read: true,
    red: false,
    bg: "/profile_two_bg.svg",
    icon: "/profile_round_two.svg",
  },
  {
    name: "Fatima",
    age: 25,
    location: "Kano",
    match: "78%",
    verified: false,
    read: false,
    red: true,
    bg: "/profile_three_bg.svg",
    icon: "/profile_round_three.svg",
  },
  {
    name: "John",
    age: 30,
    location: "Port Harcourt",
    match: "88%",
    verified: true,
    read: true,
    red: true,
    bg: "/profile_four_bg.svg",
    icon: "/profile_round_four.svg",
  },
  {
    name: "Amaka",
    age: 26,
    location: "Enugu",
    match: "81%",
    verified: false,
    read: false,
    red: true,
    bg: "/profile_two_bg.svg",
    icon: "/profile_round_two.svg",
  },
  {
    name: "Bolu",
    age: 29,
    location: "Ibadan",
    match: "89%",
    verified: true,
    read: true,
    red: true,
    bg: "/profile_four_bg.svg",
    icon: "/profile_round_four.svg",
  },
  {
    name: "Chidera",
    age: 22,
    location: "Owerri",
    match: "95%",
    verified: true,
    read: false,
    bg: "/profile_three_bg.svg",
    icon: "/profile_round_three.svg",
  },
  {
    name: "Sadiq",
    age: 27,
    location: "Sokoto",
    match: "80%",
    verified: false,
    read: true,
    red: false,
    bg: "/profile_one_bg.svg",
    icon: "/profile_round_one.svg",
  },
  {
    name: "Grace",
    age: 24,
    location: "Benin",
    match: "87%",
    verified: true,
    read: false,
    red: true,
    bg: "/profile_two_bg.svg",
    icon: "/profile_round_two.svg",
  },
  {
    name: "Uchenna",
    age: 31,
    location: "Awka",
    match: "79%",
    verified: false,
    read: true,
    bg: "/profile_three_bg.svg",
    icon: "/profile_round_three.svg",
  },
  {
    name: "Amina",
    age: 23,
    location: "Kaduna",
    match: "90%",
    verified: true,
    read: false,
    red: true,
    bg: "/profile_one_bg.svg",
    icon: "/profile_round_one.svg",
  },
  {
    name: "Olu",
    age: 28,
    location: "Ilorin",
    match: "85%",
    verified: false,
    read: true,
    red: true,
    bg: "/profile_one_bg.svg",
    icon: "/profile_round_one.svg",
  },
  {
    name: "Esther",
    age: 27,
    location: "Calabar",
    match: "83%",
    verified: true,
    read: false,
    red: true,
    bg: "/profile_one_bg.svg",
    icon: "/profile_round_one.svg",
  },
  {
    name: "Paul",
    age: 32,
    location: "Jos",
    match: "91%",
    verified: false,
    read: true,
    red: true,
    bg: "/profile_three_bg.svg",
    icon: "/profile_round_three.svg",
  },
  {
    name: "Tunde",
    age: 26,
    location: "Abeokuta",
    match: "86%",
    verified: true,
    read: false,
    red: false,
    bg: "/profile_two_bg.svg",
    icon: "/profile_round_two.svg",
  },
];
